packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - esbuild
  - argon2
  - better-sqlite3
  - sharp
  - "@img/sharp-linux-x64"
  - "@img/sharp-libvips-linux-x64"
  - "@img/sharp-linux-arm64"
  - "@img/sharp-libvips-linux-arm64"
